@admintoken = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3aW5nc3BhbiIsInN1YiI6ImpvaG5qc21pdGgiLCJhcHBfdXNlcl9pZCI6MSwiZW1haWwiOiJqb2huLnNtaXRoQGdtYWlsLmNvbSIsImF2YXRhciI6eyJhdmF0YXJJZCI6MSwiYXZhdGFySW1hZ2VVcmwiOiJodHRwczovL2Nkbi5waXhhYmF5LmNvbS9waG90by8yMDE3LzA1LzI1LzIxLzI2L2JpcmQtZmVlZGVyLTIzNDQ0MTRfXzQ4MC5qcGciLCJhdmF0YXJEZXNjcmlwdGlvbiI6IkJpcmRob3VzZSJ9LCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjY3NDE4MDU0fQ.Jju9ll0F1G5adHpVISX9Ix_e1ZY21VviphfOtEZx0Tw
@usertoken = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3aW5nc3BhbiIsInN1YiI6InNhbGx5am9uZXMxOTg5IiwiYXBwX3VzZXJfaWQiOjIsImVtYWlsIjoic2FsbHltam9uZXMxOTg5QGhvdG1haWwuY29tIiwiYXZhdGFyIjp7ImF2YXRhcklkIjoyLCJhdmF0YXJJbWFnZVVybCI6Imh0dHBzOi8vY2RuLnBpeGFiYXkuY29tL3Bob3RvLzIwMjIvMDkvMjkvMDgvMzkvZXVyb3BlYW4tcm9iaW4tNzQ4Njg4OV9fNDgwLmpwZyIsImF2YXRhckRlc2NyaXB0aW9uIjoiQmlyZGJhdGgifSwiYXV0aG9yaXRpZXMiOiJVU0VSIiwiZXhwIjoxNjY3NDE4MzUyfQ.kNnRMj5Vy8h4YwCZ-bSFu8YQfU_FZqn89AW-p7EN2h8

@url = http://wing-span-app.us-east-1.elasticbeanstalk.com

### Authenticate username Test (ADMIN)

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "johnjsmith",
    "password": "P@ssw0rd!"
}

### Authenticate username Test (USER)

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "sallyjones1989",
    "password": "P@ssw0rd!"
}

### Test Sighting POST Happy Path
@base_url = http://localhost:8080/api/sighting

POST {{base_url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{usertoken}}

{
    "sightingUserId": 2,
    "sightingBirdId": 4,
    "date": "2020-11-11",
    "city": "test city",
    "state": "test state",
    "daytime": false,
    "traits": [{"traitId": 1, "name": "test"}]
}

### Refresh Token Test

POST http://localhost:8080/refresh_token HTTP/1.1
Authorization: Bearer {{admintoken}}

### Create New User Test

POST http://localhost:8080/create_account HTTP/1.1
Content-Type: application/json

{
    "username": "testUser",
    "password": "P@ssw0rd!",
    "email": "bob@jones.com",
    "avatarId": 1,
    "avatarDescription": "Test",
    "avatarImageUrl": "test.com"
}

### Authenticate New User Test

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "testUser",
    "password": "P@ssw0rd!"
}

@newusertoken= eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3aW5nc3BhbiIsInN1YiI6InRlc3RVc2VyIiwiYXBwX3VzZXJfaWQiOjMsImVtYWlsIjoiYm9iQGpvbmVzLmNvbSIsImF2YXRhciI6eyJhdmF0YXJJZCI6MSwiYXZhdGFySW1hZ2VVcmwiOiJodHRwczovL2Nkbi5waXhhYmF5LmNvbS9waG90by8yMDE3LzA1LzI1LzIxLzI2L2JpcmQtZmVlZGVyLTIzNDQ0MTRfXzQ4MC5qcGciLCJhdmF0YXJEZXNjcmlwdGlvbiI6IkJpcmRob3VzZSJ9LCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2Njc0MTg2MzR9.AxFGNyVZg-jLKaUZrA0TFQ19Wt4VllF_CI_vFiz-URU

### New User Refresh Token Test

POST http://localhost:8080/refresh_token HTTP/1.1
Authorization: Bearer {{newusertoken}}

@refreshedtoken= eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3aW5nc3BhbiIsInN1YiI6InRlc3RVc2VyIiwiYXBwX3VzZXJfaWQiOjMsImVtYWlsIjoiYm9iQGpvbmVzLmNvbSIsImF2YXRhciI6eyJhdmF0YXJJZCI6MSwiYXZhdGFySW1hZ2VVcmwiOiJodHRwczovL2Nkbi5waXhhYmF5LmNvbS9waG90by8yMDE3LzA1LzI1LzIxLzI2L2JpcmQtZmVlZGVyLTIzNDQ0MTRfXzQ4MC5qcGciLCJhdmF0YXJEZXNjcmlwdGlvbiI6IkJpcmRob3VzZSJ9LCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2Njc0MTg2Nzd9.IDwP2lkqRObNq2rgV3nWVsqlOOVZ3cW087LVwPeH4kU

### New User Refreshed Token POST Test

POST {{base_url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{refreshedtoken}}

{
    "sightingUserId": 3,
    "sightingBirdId": 4,
    "date": "2020-11-11",
    "city": "test city",
    "state": "test state",
    "daytime": false,
    "traits": [{"traitId": 1, "name": "test"}]
}
